# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs all the tests"
  lane :test do
    
  end

  desc "Submit a new Beta Build to Test Flight"
  lane :beta do
    sync_code_signing(type: "appstore")    # see code signing guide for more information
    build_app(scheme: "MyApp")
    upload_to_testflight
    # crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Build a new version of the App"
  lane :release do

  end

  # "android.injected.version.code" => current_build_number
  
  desc "Deploy a new version to the App Store"
  lane :deploy do

  end
end