# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: 'assembleRelease')
    # crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Build a new version of the App"
  lane :release do
    gradle(task: 'clean')
    gradle(
      task: 'bundle',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => "GITHUB_WORKSPACE/AndroidKeystore.jks",
        "android.injected.signing.store.password" => "ANDROID_KEY_STORE_PASSWORD",
        "android.injected.signing.key.alias" => "ANDROID_KEY_ALIAS",
        "android.injected.signing.key.password" => "ANDROID_KEY_PASSWORD"
      }
    )
  end

  # "android.injected.version.code" => current_build_number
  
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end