# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: 'assembleRelease')
    # crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Build a development new version of the App"
  lane :build do
    gradle(
      task: 'clean assembleRelease',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => "ANDROID_KEY_STORE_LOCATION",
        "android.injected.signing.store.password" => ANDROID_KEY_STORE_PASSWORD,
        "android.injected.signing.key.alias" => "ANDROID_KEY_ALIAS",
        "android.injected.signing.key.password" => ANDROID_KEY_PASSWORD
      }
    )
  end

  desc "Build a release new version of the App"
  lane :release do
    gradle(
      task: 'clean bundleRelease',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => "ANDROID_KEY_STORE_LOCATION",
        "android.injected.signing.store.password" => ANDROID_KEY_STORE_PASSWORD,
        "android.injected.signing.key.alias" => "ANDROID_KEY_ALIAS",
        "android.injected.signing.key.password" => ANDROID_KEY_PASSWORD
      }
    )
  end

  desc "Deploy the new version to Playstore"
  lane :deploy do
    upload_to_play_store(
      aab: 'RUNNER_WORKSPACE/android/app/build/outputs/bundle/release/app-release.aab'
    )
  end

  # "android.injected.version.code" => current_build_number
  
end