export const CATEGORIES = {
    categories: [
        {
            id: "fbacde54-88e6-4d17-8aa9-286a716ba12f",
            name: "Frontend development",
            hourly_wage_dollars: 25,
            created_at: "2022-12-14T13:19:18.541Z",
            updated_at: "2022-12-14T13:19:18.541Z"
        },
        {
            id: "95dedd87-f0d5-46f9-8756-8946308fca77",
            name: "Backend development",
            hourly_wage_dollars: 25,
            created_at: "2022-12-14T13:19:18.541Z",
            updated_at: "2022-12-14T13:19:18.541Z"
        },
        {
            id: "a0839fc4-ee83-4b44-9372-6dcf58fa6ab7",
            name: "Full-stack development",
            hourly_wage_dollars: 28,
            created_at: "2022-12-14T13:19:18.541Z",
            updated_at: "2022-12-14T13:19:18.541Z"
        },
    ]
}

export const SKILLS = {
    page: 1,
    limit: 500,
    total_count: 220,
    items: [
        {
            id: "4076a364-bc3b-4a7a-b1ae-3354a9f91273",
            name: "BLOCKCHAIN_DEVELOPMENT",
            created_at: "2023-08-29T15:00:00.000Z"
        },
        {
            id: "23c588e9-1472-4fda-a083-c495b4d03c27",
            name: "PLUTUS",
            created_at: "2023-08-29T15:00:00.000Z"
        },
        {
            id: "3bfbc833-f003-4e24-9366-7af290024710",
            name: "HASKELL",
            created_at: "2023-08-29T15:00:00.000Z"
        },
    ]
}

export const CONNECT = {
    link: {
        object: "account_link",
        created: 1744635445,
        expires_at: 1744635745,
        url: "https://connect.stripe.com/setup/e/acct_1RDmZhC22vVAHrbW/EHR6oyvPWScO"
    }
}

export const ORG_ODENTITY = {
    id: "1396c403-1ade-4c40-b0d1-4680059a46c5",
    name: "OrganizationTest",
    bio: null,
    description: null,
    email: "imshantik@gmal.com",
    phone: null,
    city: "Tehran",
    type: "SOCIAL",
    address: null,
    website: "https://www.test",
    created_at: "2025-02-27T13:16:43.884Z",
    updated_at: "2025-02-27T13:16:43.884Z",
    social_causes: [
        "EDUCATION",
        "BULLYING",
        "SUBSTANCE_ABUSE",
        "DISABILITY"
    ],
    followers: 1,
    followings: 1,
    country: "IR",
    wallet_address: null,
    impact_points: 0,
    mission: null,
    culture: null,
    image: null,
    cover_image: null,
    mobile_country_code: null,
    created_by: "035f724e-5824-4129-8ed6-96c6dda81a3a",
    shortname: "organizationtest",
    old_id: null,
    status: "ACTIVE",
    search_tsv: "'imshantik@gmal.com':1 'organizationtest':2,3 'tehran':4",
    other_party_id: null,
    other_party_title: null,
    other_party_url: null,
    geoname_id: null,
    verified_impact: false,
    hiring: true,
    size: "F",
    industry: "Oil and Gas",
    did: null,
    verified: false,
    impact_detected: false,
    following: false,
    follower: false,
    connection_status: null,
    connection_id: null,
    benefits: null,
    recommendations: null,
    connections: 0
}

export const SERCVISES = {
    page: 1,
    limit: 10,
    total_count: 36,
    items: [
        {
            id: "916f4197-8846-437a-82d5-76180ec0bb82",
            identity_id: "48ef808d-85eb-4e6d-a8a5-853cd93abc4d",
            description: "dded",
            project_type: null,
            project_length: "1_WEEK",
            payment_currency: "JPY",
            payment_range_lower: "55",
            payment_range_higher: "55",
            experience_level: null,
            created_at: "2025-02-26T09:10:34.933Z",
            updated_at: "0001-01-01T00:00:00.000Z",
            deleted_at: null,
            status: "ACTIVE",
            payment_type: null,
            payment_scheme: null,
            title: "service test222",
            expires_at: null,
            country: null,
            skills: [
                "JAVASCRIPT"
            ],
            causes_tags: [],
            old_id: null,
            other_party_id: null,
            other_party_title: null,
            other_party_url: null,
            remote_preference: null,
            search_tsv: "'dded':3 'servic':1 'test222':2",
            city: null,
            weekly_hours_lower: null,
            weekly_hours_higher: null,
            commitment_hours_lower: "22",
            commitment_hours_higher: "22",
            geoname_id: null,
            job_category_id: "a0839fc4-ee83-4b44-9372-6dcf58fa6ab7",
            impact_job: true,
            promoted: false,
            kind: "SERVICE",
            payment_mode: "FIAT",
            identity_type: "users",
            identity_meta: {
                id: "48ef808d-85eb-4e6d-a8a5-853cd93abc4d",
                city: "Arinsal",
                name: "Nina N",
                email: "testazintest2@gmail.com",
                avatar: null,
                status: "ACTIVE",
                address: null,
                country: "AD",
                username: "testazintest2",
                open_to_work: false,
                is_contributor: true,
                wallet_address: "0x6990bf996E984cffde6EbCAb6AC8723c95069719",
                identity_verified: false,
                open_to_volunteer: false
            },
            job_category: {
                id: "a0839fc4-ee83-4b44-9372-6dcf58fa6ab7",
                name: "Full-stack development",
                hourly_wage_dollars: 28,
                created_at: "2022-12-14T13:19:18.541708+00:00",
                updated_at: "2022-12-14T13:19:18.541708+00:00"
            },
            work_samples: [],
            applicants: 0,
            missions: 0,
            saved: false,
            not_interested: false
        },
        {
            id: "9992c6d1-7cbf-436f-8008-9eb7c9b7e29a",
            identity_id: "48ef808d-85eb-4e6d-a8a5-853cd93abc4d",
            description: "dded",
            project_type: null,
            project_length: "1_WEEK",
            payment_currency: "JPY",
            payment_range_lower: "55",
            payment_range_higher: "55",
            experience_level: null,
            created_at: "2025-03-11T21:36:38.021Z",
            updated_at: "0001-01-01T00:00:00.000Z",
            deleted_at: null,
            status: "ACTIVE",
            payment_type: null,
            payment_scheme: null,
            title: "service test contract",
            expires_at: null,
            country: null,
            skills: [
                "JAVASCRIPT"
            ],
            causes_tags: [],
            old_id: null,
            other_party_id: null,
            other_party_title: null,
            other_party_url: null,
            remote_preference: null,
            search_tsv: "'contract':3 'dded':4 'servic':1 'test':2",
            city: null,
            weekly_hours_lower: null,
            weekly_hours_higher: null,
            commitment_hours_lower: "22",
            commitment_hours_higher: "22",
            geoname_id: null,
            job_category_id: "a0839fc4-ee83-4b44-9372-6dcf58fa6ab7",
            impact_job: true,
            promoted: false,
            kind: "SERVICE",
            payment_mode: "FIAT",
            identity_type: "users",
            identity_meta: {
                id: "48ef808d-85eb-4e6d-a8a5-853cd93abc4d",
                city: "Arinsal",
                name: "Nina N",
                email: "testazintest2@gmail.com",
                avatar: null,
                status: "ACTIVE",
                address: null,
                country: "AD",
                username: "testazintest2",
                open_to_work: false,
                is_contributor: true,
                wallet_address: "0x6990bf996E984cffde6EbCAb6AC8723c95069719",
                identity_verified: false,
                open_to_volunteer: false
            },
            job_category: {
                id: "a0839fc4-ee83-4b44-9372-6dcf58fa6ab7",
                name: "Full-stack development",
                hourly_wage_dollars: 28,
                created_at: "2022-12-14T13:19:18.541708+00:00",
                updated_at: "2022-12-14T13:19:18.541708+00:00"
            },
            work_samples: [],
            applicants: 0,
            missions: 0,
            saved: false,
            not_interested: false
        },
        {
            id: "73f25598-13e4-4900-8482-57c33bbbb3b5",
            identity_id: "48ef808d-85eb-4e6d-a8a5-853cd93abc4d",
            description: "sdfghjknml,.",
            project_type: null,
            project_length: "1_WEEK",
            payment_currency: "JPY",
            payment_range_lower: "65",
            payment_range_higher: "65",
            experience_level: null,
            created_at: "2025-03-11T21:41:44.062Z",
            updated_at: "0001-01-01T00:00:00.000Z",
            deleted_at: null,
            status: "ACTIVE",
            payment_type: null,
            payment_scheme: null,
            title: "service test contract2",
            expires_at: null,
            country: null,
            skills: [
                "JAVASCRIPT"
            ],
            causes_tags: [],
            old_id: null,
            other_party_id: null,
            other_party_title: null,
            other_party_url: null,
            remote_preference: null,
            search_tsv: "'contract2':3 'sdfghjknml':4 'servic':1 'test':2",
            city: null,
            weekly_hours_lower: null,
            weekly_hours_higher: null,
            commitment_hours_lower: "22",
            commitment_hours_higher: "22",
            geoname_id: null,
            job_category_id: "a2da048a-89ad-4c1e-a5e6-759f7e4f1bf2",
            impact_job: true,
            promoted: false,
            kind: "SERVICE",
            payment_mode: "FIAT",
            identity_type: "users",
            identity_meta: {
                id: "48ef808d-85eb-4e6d-a8a5-853cd93abc4d",
                city: "Arinsal",
                name: "Nina N",
                email: "testazintest2@gmail.com",
                avatar: null,
                status: "ACTIVE",
                address: null,
                country: "AD",
                username: "testazintest2",
                open_to_work: false,
                is_contributor: true,
                wallet_address: "0x6990bf996E984cffde6EbCAb6AC8723c95069719",
                identity_verified: false,
                open_to_volunteer: false
            },
            job_category: {
                id: "a2da048a-89ad-4c1e-a5e6-759f7e4f1bf2",
                name: "Blockchain development",
                hourly_wage_dollars: 44.5,
                created_at: "2022-12-14T13:19:18.541708+00:00",
                updated_at: "2022-12-14T13:19:18.541708+00:00"
            },
            work_samples: [],
            applicants: 0,
            missions: 0,
            saved: false,
            not_interested: false
        },
    ]
}

export const SERVICE_DETAIL = {
    id: "916f4197-8846-437a-82d5-76180ec0bb82",
    title: "service test222",
    description: "dded",
    project_type: null,
    project_length: "1_WEEK",
    payment_currency: "JPY",
    payment_range_lower: "55",
    payment_range_higher: "55",
    experience_level: null,
    status: "ACTIVE",
    payment_type: null,
    payment_scheme: null,
    country: null,
    skills: [
        "JAVASCRIPT"
    ],
    causes_tags: [],
    old_id: null,
    other_party_id: null,
    other_party_title: null,
    other_party_url: null,
    remote_preference: null,
    search_tsv: "'dded':3 'servic':1 'test222':2",
    city: null,
    weekly_hours_lower: null,
    weekly_hours_higher: null,
    commitment_hours_lower: "22",
    commitment_hours_higher: "22",
    payment_mode: "FIAT",
    geoname_id: null,
    job_category_id: "a0839fc4-ee83-4b44-9372-6dcf58fa6ab7",
    impact_job: true,
    promoted: false,
    kind: "SERVICE",
    work_samples: [],
    identity: {
        id: "48ef808d-85eb-4e6d-a8a5-853cd93abc4d",
        type: "users",
        meta: {
            address: null,
            avatar: null,
            city: "Arinsal",
            country: "AD",
            email: "testazintest2@gmail.com",
            id: "48ef808d-85eb-4e6d-a8a5-853cd93abc4d",
            identity_verified: false,
            is_contributor: true,
            name: "Nina N",
            open_to_volunteer: false,
            open_to_work: false,
            status: "ACTIVE",
            username: "testazintest2",
            wallet_address: "0x6990bf996E984cffde6EbCAb6AC8723c95069719"
        },
        created_at: "2022-11-03T06:22:49.394579Z"
    },
    created_at: "2025-02-26T09:10:34.933986Z",
    updated_at: "0001-01-01T00:00:00Z",
    expires_at: null,
    deleted_at: null,
    job_category: {
        id: "a0839fc4-ee83-4b44-9372-6dcf58fa6ab7",
        name: "Full-stack development",
        hourly_wage_dollars: 28,
        created_at: "2022-12-14T13:19:18.541708+00:00",
        updated_at: "2022-12-14T13:19:18.541708+00:00"
    }
}

export const IDENTITY_SERVICES = [
    {
        id: "1396c403-1ade-4c40-b0d1-4680059a46c5",
        type: "organizations",
        meta: {
            id: "1396c403-1ade-4c40-b0d1-4680059a46c5",
            city: "Tehran",
            name: "OrganizationTest",
            email: "imshantik@gmal.com",
            image: null,
            hiring: true,
            status: "ACTIVE",
            address: null,
            country: "IR",
            mission: null,
            verified: false,
            shortname: "organizationtest",
            description: null,
            wallet_address: null,
            verified_impact: false
        },
        created_at: "2025-02-27T13:16:43.884Z",
        primary: false,
        current: true,
        verification_status: "PENDING"
    },
    {
        id: "3a4aa78b-9bf1-41bc-ab9c-1ae4fd6ebc7d",
        type: "organizations",
        meta: {
            id: "3a4aa78b-9bf1-41bc-ab9c-1ae4fd6ebc7d",
            city: "Tehran",
            name: "shant company",
            email: "mockMail@gmail.com",
            image: null,
            hiring: false,
            status: "ACTIVE",
            address: null,
            country: "IR",
            mission: null,
            verified: false,
            shortname: "shantik",
            description: null,
            wallet_address: null,
            verified_impact: false
        },
        created_at: "2025-02-28T08:24:45.311Z",
        primary: false,
        current: false,
        verification_status: null
    },
    {
        current: false,
        primary: true,
        id: "035f724e-5824-4129-8ed6-96c6dda81a3a",
        type: "users",
        meta: {
            id: "035f724e-5824-4129-8ed6-96c6dda81a3a",
            city: null,
            name: null,
            email: "imshantik@gmail.com",
            avatar: null,
            status: "ACTIVE",
            address: null,
            country: null,
            username: "imshantik5140",
            open_to_work: false,
            is_contributor: null,
            wallet_address: null,
            identity_verified: false,
            open_to_volunteer: true
        },
        created_at: "2025-02-27T10:59:24.278Z",
        verification_status: "PENDING"
    }
]