export const IDENTITIES = [
  {
    id: 'deb0e215-e2cd-4d7f-9ae3-bc7141acd3cf',
    type: 'organizations',
    meta: {
      id: 'deb0e215-e2cd-4d7f-9ae3-bc7141acd3cf',
      city: 'Abu Dhabi, Abu Dhabi',
      name: 'sanaz company',
      email: 'mahmoudisanaz59@gmail.com',
      image: null,
      hiring: false,
      status: 'ACTIVE',
      address: null,
      country: 'AE',
      mission: 'mission',
      shortname: 'sanaz_company3945',
      description: 'afdfasf',
      wallet_address: null,
      verified_impact: false,
    },
    created_at: '2023-07-11T18:39:09.046Z',
    primary: false,
    current: false,
  },
  {
    current: true,
    primary: true,
    id: '20b07c1c-b142-4ee3-a87f-122aa99a7659',
    type: 'users',
    meta: {
      id: '20b07c1c-b142-4ee3-a87f-122aa99a7659',
      city: 'Tehran, Tehran Province',
      name: 'Sanaz Mahmoudi',
      email: 'mahmoudisanaz59@gmail.com',
      avatar: 'https://socious-new.s3.ap-northeast-1.amazonaws.com/c42678cd9b86e277fc0a045483304b4e.jpg',
      status: 'ACTIVE',
      address: null,
      country: 'IR',
      username: 'satanmourner',
      open_to_work: false,
      wallet_address: null,
      open_to_volunteer: false,
    },
    created_at: '2023-03-19T19:57:01.211Z',
  },
];

export const PROJECTS = {
  page: 1,
  limit: 5,
  total_count: 1,
  items: [
    {
      id: 'fe408ad8-9677-42fa-abde-7b7619053479',
      identity_id: 'c9c42045-5cef-48b3-804f-a7315feded34',
      description: 'adads',
      project_type: 'ONE_OFF',
      project_length: 'LESS_THAN_A_DAY',
      payment_currency: 'USD',
      payment_range_lower: '12',
      payment_range_higher: '13',
      experience_level: 0,
      created_at: '2024-03-08T11:37:36.735Z',
      updated_at: '2024-03-14T07:07:23.958Z',
      deleted_at: null,
      status: 'ACTIVE',
      payment_type: 'PAID',
      payment_scheme: 'FIXED',
      title: 'Demo Retain to offered tab',
      expires_at: null,
      country: null,
      skills: ['BLOCKCHAIN_DEVELOPMENT'],
      causes_tags: ['SOCIAL'],
      old_id: null,
      other_party_id: null,
      other_party_title: null,
      other_party_url: null,
      remote_preference: 'ONSITE',
      search_tsv: "'adads':6 'demo':1 'offered':4 'retain':2 'tab':5 'to':3",
      city: null,
      weekly_hours_lower: null,
      weekly_hours_higher: null,
      commitment_hours_lower: '12',
      commitment_hours_higher: '122',
      geoname_id: null,
      job_category_id: 'fbacde54-88e6-4d17-8aa9-286a716ba12f',
      impact_job: true,
      promoted: false,
      identity_type: 'organizations',
      identity_meta: {
        id: 'c9c42045-5cef-48b3-804f-a7315feded34',
        city: 'San Pablo',
        name: 'Beat Childhood Cancer',
        email: 'beat@childhoodcancer.com',
        image: 'https://socious-new.s3.ap-northeast-1.amazonaws.com/b1d9475807b80280863ebc4c4f2cf1a1.jpg',
        hiring: false,
        status: 'ACTIVE',
        address: null,
        country: 'PH',
        mission:
          "THIS IS SUMMMARY:\n\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        shortname: 'beat_childhood_cancer3553',
        description: null,
        wallet_address: null,
        verified_impact: false,
      },
      job_category: {
        id: 'fbacde54-88e6-4d17-8aa9-286a716ba12f',
        name: 'Frontend development',
        hourly_wage_dollars: 25,
        created_at: '2022-12-14T13:19:18.541708+00:00',
        updated_at: '2022-12-14T13:19:18.541708+00:00',
      },
      missions: 0,
      applicants: 3,
    },
  ],
};

export const PROJECT = {
  id: 'fe408ad8-9677-42fa-abde-7b7619053479',
  identity_id: 'c9c42045-5cef-48b3-804f-a7315feded34',
  description: 'adads',
  project_type: 'ONE_OFF',
  project_length: 'LESS_THAN_A_DAY',
  payment_currency: 'USD',
  payment_range_lower: '12',
  payment_range_higher: '13',
  experience_level: 0,
  created_at: '2024-03-08T11:37:36.735Z',
  updated_at: '2024-03-14T07:07:23.958Z',
  deleted_at: null,
  status: 'ACTIVE',
  payment_type: 'PAID',
  payment_scheme: 'FIXED',
  title: 'Demo Retain to offered tab',
  expires_at: null,
  country: null,
  skills: ['BLOCKCHAIN_DEVELOPMENT'],
  causes_tags: ['SOCIAL'],
  old_id: null,
  other_party_id: null,
  other_party_title: null,
  other_party_url: null,
  remote_preference: 'ONSITE',
  search_tsv: "'adads':6 'demo':1 'offered':4 'retain':2 'tab':5 'to':3",
  city: null,
  weekly_hours_lower: null,
  weekly_hours_higher: null,
  commitment_hours_lower: '12',
  commitment_hours_higher: '122',
  geoname_id: null,
  job_category_id: 'fbacde54-88e6-4d17-8aa9-286a716ba12f',
  impact_job: true,
  promoted: false,
  identity_type: 'organizations',
  identity_meta: {
    id: 'c9c42045-5cef-48b3-804f-a7315feded34',
    city: 'San Pablo',
    name: 'Beat Childhood Cancer',
    email: 'beat@childhoodcancer.com',
    image: 'https://socious-new.s3.ap-northeast-1.amazonaws.com/b1d9475807b80280863ebc4c4f2cf1a1.jpg',
    hiring: false,
    status: 'ACTIVE',
    address: null,
    country: 'PH',
    mission:
      "THIS IS SUMMMARY:\n\nLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    shortname: 'beat_childhood_cancer3553',
    description: null,
    wallet_address: null,
    verified_impact: false,
  },
  job_category: {
    id: 'fbacde54-88e6-4d17-8aa9-286a716ba12f',
    name: 'Frontend development',
    hourly_wage_dollars: 25,
    created_at: '2022-12-14T13:19:18.541708+00:00',
    updated_at: '2022-12-14T13:19:18.541708+00:00',
  },
  applicants: 3,
  missions: 0,
  applied: false,
};
